---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp jac.html $DEPLOYPATH
    - /bin/cp pawsembly.html $DEPLOYPATH
    - /bin/cp redtale.html $DEPLOYPATH
    - /bin/cp redtaleapi.html $DEPLOYPATH